# Postgres config reference:
config:
  send_anonymous_usage_stats: False
  use_colors: True
meltano:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_POSTGRES_HOST') }}"
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      password: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: "{{ env_var('DBT_POSTGRES_PORT') | int }}"
      dbname: "{{ env_var('DBT_POSTGRES_DBNAME', '') }}"
      schema: "{{ env_var('DBT_POSTGRES_SCHEMA') }}"
      threads: 2
      keepalives_idle: 0
      connect_timeout: 10
