services:
  vscode:
    build:
      context: .
      dockerfile: vscode.Dockerfile
    tty: true
    volumes:
      - ..:/workspace:cached

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres: